name: pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'

permissions:
    contents: write
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.18
        with:
          primary_branch: 'main'
          enable_github_releases: true
          init_version: rc/0.4.0
          release_tag_prefix: "v"
